// Generated by `supabase gen types typescript --linked` via `npm run db:types`.
// Do not edit by hand — re-run the generator after applying migrations.
// Until first generation, this file exports a permissive stub so the
// package resolves; running `npm run db:types` will overwrite it.

export type Database = {
  public: { Tables: Record<string, never>; Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never> };
};
